image:
  file: .gitpod.Dockerfile
tasks:
  - command: kotlinc hello.kt && kotlin HelloKt
vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.0:9xQZtwTUg4bdXHCMyxM7vQ==
    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
